"""
Constants and naming functions for GMA.
"""
import os

###
#
# GENERAL
#
###


COVER_THRESHOLD = 1e-6

DATA_PATH = os.path.join(os.getcwd(), 'dat/topologies/')
# DATA TYPE CONSTANTS
ALLOCATION = 0
SHORTEST_PATH = 1
ALLOCATION_MATRIX = 2
PATH_LENGTHS = 3
PATH_COUNTS = 4
TOPOLOGY = 5
DIAMETER = 6
COMPARISON = 7
COVER = 8
DEGREE = 9

# DATA TYPE - FILE TYPE MAP
FILE_TYPE = [
    'json',
    'json',
    'pkl',
    'pkl',
    'pkl',
    'xml',
    'txt',
    'json',
    'json',
    'json'
]


VERBOSITY = 2



###
#
# GMA
#
###

# AS business relationships
PEER = "peer"
CUST = "customer"
PROV = "provider"
TYPE = "type"

# # Types: these are only for the ones generated by NX
# TYPE_PEER = "peer"
# TYPE_TRANSIT = "transit"
# # Dictionary values
# CUSTOMER = "customer"

# Capacity
BW = "capacity"
INT_BW = "internal_capacity"  # Internal bandwidth of a node
MAX_ROUNDS = 10

# Precision with which to compute the allocations
PRECISION = 12

